use test;
db.zips.aggregate([  
   {  
      $project:{  
         first_char:{  
            $substr:[  
               "$city",
               0,
               1
            ]
         },
         pop:"$pop"
      }
   },
   {  
      $group:{  
         "_id":"$first_char",
         tot_pop:{  
            $sum:"$pop"
         }
      }
   },
   {  
      $match:{  
         "_id":{  
            $in:[  
               "B",
               "D",
               "O",
               "G",
               "N",
               "M"
            ]
         }
      }
   },
   {  
      $group:{  
         "_id":null,
         "tot_pop":{  
            $sum:"$tot_pop"
         }
      }
   }
])
